### PR TITLE
Fixed URL for RR Lyrae dataset download

### PR DESCRIPTION
**Pull request by jeanlucmargot**
Fixed and tested.

### CODE REVIEW

**Comment by bsipocz** [comment]
There is a redirect in place for the `master`-->`main` renames. Do you run into any issues with it.

Also, we have just recently moved the main functionality upstream, Given the recent move of the main functionality upstream, also the potential plans of moving the remaining ones and archiving the repo we may not fixing this?

(I suppose, we could also move the datasets functions upstream to astroML proper?)

**Comment by jeanlucmargot** [comment]
Thank you.  A senior astrophysics undergraduate student was unable to install/run the software.  I reproduced the problem independently.  Install works with the fix, it does not without the fix.

**Comment by bsipocz** [comment]
Hmm, I see. Have your student tried to install the released version from pypi, or what is currently on the master branch? I, too, run into a HTTPError when 0.3 is installed, as it tries to fetch the data from the mpia link, but when I install the dev version with e.g. `pip install git+https://github.com/astroML/gatspy`, it all seems to work.

**Comment by jeanlucmargot** [comment]
My student indicates that he installed with pip and still had the issue.

**Comment by bsipocz** [comment]
I still don't think this would make a difference, but OK with merging this PR. Eventually, I'll move these data-fetching functions upstream to astroML (https://github.com/astroML/gatspy/issues/38#issuecomment-1538466826) as part of the retirement of this package.

**Pull request merged**
